import { palette } from "./palette.js"

export const cozyDark = {
  $schema: "vscode://schemas/color-theme",
  type: "dark",
  colors: {
    "activityBar.background": palette.ebonyClay,
    "activityBar.border": palette.limedSpruce,
    "activityBar.foreground": palette.ecruWhite,
    "activityBarBadge.background": palette.mineralGreen,
    "activityBarBadge.foreground": `${palette.ecruWhite}99`,
    "badge.background": palette.mineralGreen,
    "badge.foreground": palette.ecruWhite,
    "breadcrumb.activeSelectionForeground": palette.riverBed,
    "breadcrumb.focusForeground": palette.heather,
    "breadcrumb.foreground": palette.bermudaGray,
    "breadcrumbPicker.background": palette.outerSpace,
    "button.background": palette.ebonyClay,
    "button.foreground": palette.heather,
    "button.hoverBackground": palette.mineralGreen,
    contrastBorder: `${palette.ecruWhite}00`,
    "debugExceptionWidget.background": palette.ebonyClay,
    "debugExceptionWidget.border": palette.heather,
    "debugIcon.stopForeground": palette.deepBlush,
    "debugToolBar.background": palette.ebonyClay,
    descriptionForeground: palette.heather,
    "diffEditor.insertedTextBackground": palette.mineralGreen2,
    "diffEditor.insertedTextBorder": palette.limedSpruce,
    "diffEditor.removedTextBackground": palette.donJuan,
    "diffEditor.removedTextBorder": palette.limedSpruce,
    "dropdown.background": palette.riverBed,
    "dropdown.border": palette.riverBed,
    "dropdown.foreground": palette.ecruWhite,
    "editor.background": palette.ebonyClay,
    "editor.findMatchBackground": `${palette.heather}80`,
    "editor.findMatchHighlightBackground": `${palette.heather}30`,
    "editor.findRangeHighlightBackground": palette.blueDianne,
    "editor.foreground": palette.heather,
    "editor.hoverHighlightBackground": palette.limedSpruce,
    "editor.inactiveSelectionBackground": palette.ebonyClay2,
    "editor.lineHighlightBackground": palette.ebonyClay3,
    "editor.lineHighlightBorder": palette.ebonyClay3,
    "editor.rangeHighlightBackground": palette.ebonyClay3,
    "editor.selectionBackground": palette.limedSpruce2,
    "editor.selectionHighlightBackground": palette.ebonyClay3,
    "editor.wordHighlightBackground": palette.mako,
    "editor.wordHighlightStrongBackground": palette.riverBed,
    "editorBracketMatch.background": palette.kashmirBlue,
    "editorBracketMatch.border": palette.astronaut,
    "editorBracketHighlight.foreground1": palette.tacao,
    "editorBracketHighlight.foreground2": palette.tapestry,
    "editorBracketHighlight.foreground3": palette.dodgerBlue,
    "editorCodeLens.foreground": palette.heather,
    "editorCursor.foreground": palette.heather,
    "editorError.border": palette.limedSpruce,
    "editorError.foreground": palette.deepBlush,
    "editorGroup.border": palette.ebonyClay,
    "editorGroup.dropBackground": palette.limedSpruce,
    "editorGroup.emptyBackground": palette.ebonyClay,
    "editorGroupHeader.noTabsBackground": palette.limedSpruce,
    "editorGroupHeader.tabsBackground": palette.mirage,
    "editorGroupHeader.tabsBorder": palette.limedSpruce,
    "editorGutter.addedBackground": palette.vistaBlue,
    "editorGutter.background": palette.ebonyClay,
    "editorGutter.deletedBackground": palette.deepBlush,
    "editorGutter.modifiedBackground": palette.astronaut,
    "editorHoverWidget.background": palette.mirage2,
    "editorHoverWidget.border": palette.limedSpruce,
    "editorIndentGuide.activeBackground": palette.doveGray,
    "editorIndentGuide.background": palette.outerSpace,
    "editorLineNumber.foreground": palette.riverBed,
    "editorLink.activeForeground": palette.heather,
    "editorMarkerNavigation.background": palette.ebonyClay,
    "editorMarkerNavigationError.background": palette.cabaret,
    "editorMarkerNavigationWarning.background": palette.rawSienna,
    "editorOverviewRuler.border": palette.limedSpruce,
    "editorOverviewRuler.commonContentForeground": `${palette.tacao}55`,
    "editorOverviewRuler.currentContentForeground": `${palette.amaranth}55`,
    "editorOverviewRuler.incomingContentForeground": `${palette.harlequin}55`,
    "editorRuler.foreground": palette.cello,
    "editorSuggestWidget.background": palette.mirage2,
    "editorSuggestWidget.border": palette.mirage2,
    "editorSuggestWidget.foreground": palette.heather,
    "editorSuggestWidget.highlightForeground": palette.tacao,
    "editorSuggestWidget.selectedBackground": palette.outerSpace,
    "editorWarning.border": `${palette.ecruWhite}00`,
    "editorWarning.foreground": palette.tacao,
    "editorWhitespace.foreground": `${palette.ecruWhite}1a`,
    "editorWidget.background": palette.mirage2,
    "editorWidget.border": palette.limedSpruce,
    errorForeground: palette.deepBlush,
    "extensionButton.prominentBackground": palette.mineralGreen,
    "extensionButton.prominentForeground": palette.ecruWhite,
    "extensionButton.prominentHoverBackground": palette.mineralGreen,
    focusBorder: palette.limedSpruce,
    foreground: palette.heather,
    "gitDecoration.addedResourceForeground": palette.aquaForest,
    "gitDecoration.conflictingResourceForeground": palette.scooter,
    "gitDecoration.deletedResourceForeground": palette.deepBlush,
    "gitDecoration.ignoredResourceForeground": palette.riverBed,
    "gitDecoration.modifiedResourceForeground": palette.tacao,
    "gitDecoration.untrackedResourceForeground": palette.vistaBlue,
    "input.background": palette.limedSpruce,
    "input.border": palette.limedSpruce,
    "input.foreground": palette.heather,
    "input.placeholderForeground": palette.heather,
    "inputOption.activeBorder": palette.dodgerBlue2,
    "inputValidation.errorBackground": palette.deepBlush,
    "inputValidation.errorBorder": palette.cabaret,
    "inputValidation.errorForeground": palette.ecruWhite,
    "inputValidation.infoBackground": palette.malibu,
    "inputValidation.infoBorder": palette.dodgerBlue2,
    "inputValidation.warningBackground": palette.tacao,
    "inputValidation.warningBorder": palette.rawSienna,
    "inputValidation.warningForeground": palette.ebonyClay4,
    "list.activeSelectionBackground": palette.ebonyClay4,
    "list.activeSelectionForeground": palette.heather,
    "list.activeSelectionIconForeground": palette.ecruWhite,
    "list.dropBackground": palette.limedSpruce,
    "list.focusBackground": palette.limedSpruce,
    "list.focusForeground": palette.heather,
    "list.highlightForeground": palette.cuttySark,
    "list.hoverBackground": palette.ebonyClay4,
    "list.hoverForeground": palette.heather,
    "list.inactiveSelectionBackground": palette.limedSpruce,
    "list.inactiveSelectionForeground": palette.heather,
    "menu.background": palette.shark,
    "menu.foreground": palette.silver,
    "minimap.errorHighlight": palette.deepBlush,
    "minimap.selectionHighlight": palette.cuttySark,
    "minimap.warningHighlight": palette.rawSienna,
    "minimapGutter.addedBackground": palette.vistaBlue,
    "minimapGutter.deletedBackground": palette.deepBlush,
    "minimapSlider.background": `${palette.mineralGreen}40`,
    "minimapSlider.hoverBackground": `${palette.mineralGreen}66`,
    "notificationCenterHeader.background": palette.gableGreen,
    "notificationLink.foreground": palette.bermudaGray,
    "notifications.background": palette.mirage2,
    "notifications.border": palette.gableGreen,
    "notifications.foreground": palette.heather,
    "notificationsErrorIcon.foreground": palette.deepBlush,
    "notificationsInfoIcon.foreground": palette.heather,
    "notificationsWarningIcon.foreground": palette.rawSienna,
    "panel.background": palette.bunker,
    "panel.border": palette.bunker,
    "panelTitle.activeBorder": palette.riverBed,
    "panelTitle.activeForeground": palette.riverBed,
    "panelTitle.inactiveForeground": palette.heather,
    "peekView.border": palette.limedSpruce,
    "peekViewEditor.background": palette.mirage2,
    "peekViewEditor.matchHighlightBackground": palette.limedSpruce,
    "peekViewEditorGutter.background": palette.limedSpruce,
    "peekViewResult.background": palette.mirage2,
    "peekViewResult.fileForeground": palette.heather,
    "peekViewResult.lineForeground": palette.ecruWhite,
    "peekViewResult.matchHighlightBackground": palette.limedSpruce,
    "peekViewResult.selectionBackground": palette.limedSpruce,
    "peekViewResult.selectionForeground": palette.ecruWhite,
    "peekViewTitle.background": palette.mirage2,
    "peekViewTitleDescription.foreground": palette.heather,
    "peekViewTitleLabel.foreground": palette.mineralGreen,
    "pickerGroup.border": palette.limedSpruce,
    "pickerGroup.foreground": palette.heather,
    "ports.iconRunningProcessForeground": palette.apple,
    "progressBar.background": palette.mineralGreen,
    "scrollbar.shadow": `${palette.black}00`,
    "scrollbarSlider.activeBackground": palette.limedSpruce,
    "scrollbarSlider.background": `${palette.riverBed}80`,
    "scrollbarSlider.hoverBackground": `${palette.riverBed}cc`,
    "selection.background": palette.azureRadiance,
    "sideBar.background": palette.bunker,
    "sideBar.border": palette.ebonyClay,
    "sideBar.foreground": palette.heather,
    "sideBarSectionHeader.background": palette.ebonyClay,
    "sideBarSectionHeader.border": `${palette.silver}33`,
    "sideBarSectionHeader.foreground": palette.heather,
    "sideBarTitle.foreground": palette.heather,
    "statusBar.background": palette.bunker,
    "statusBar.border": palette.ebonyClay,
    "statusBar.debuggingBackground": palette.heather,
    "statusBar.debuggingForeground": palette.bunker,
    "statusBar.foreground": palette.heather,
    "statusBar.noFolderBackground": palette.bunker,
    "statusBar.noFolderForeground": palette.heather,
    "statusBarItem.activeBackground": palette.limedSpruce,
    "statusBarItem.hoverBackground": palette.limedSpruce,
    "statusBarItem.prominentBackground": palette.bunker,
    "statusBarItem.prominentHoverBackground": palette.limedSpruce,
    "statusBarItem.remoteBackground": palette.genoa,
    "statusBarItem.remoteForeground": palette.ecruWhite,
    "tab.activeBackground": palette.ebonyClay,
    "tab.activeBorder": palette.ebonyClay,
    "tab.activeForeground": palette.ecruWhite,
    "tab.border": palette.bunker,
    "tab.inactiveBackground": palette.bunker,
    "tab.inactiveForeground": palette.heather,
    "tab.lastPinnedBorder": `${palette.silver}33`,
    "tab.unfocusedActiveForeground": palette.heather,
    "tab.unfocusedInactiveForeground": palette.heather,
    "terminal.ansiBlack": palette.riverBed,
    "terminal.ansiBlue": palette.dodgerBlue2,
    "terminal.ansiBrightBlack": palette.riverBed,
    "terminal.ansiBrightBlue": palette.dodgerBlue2,
    "terminal.ansiBrightCyan": palette.turquoiseBlue,
    "terminal.ansiBrightGreen": palette.vistaBlue,
    "terminal.ansiBrightMagenta": palette.fuchsiaPink,
    "terminal.ansiBrightRed": palette.cabaret,
    "terminal.ansiBrightWhite": palette.ecruWhite,
    "terminal.ansiBrightYellow": palette.tacao,
    "terminal.ansiCyan": palette.turquoiseBlue,
    "terminal.ansiGreen": palette.vistaBlue,
    "terminal.ansiMagenta": palette.hibiscus,
    "terminal.ansiRed": palette.cabaret,
    "terminal.ansiWhite": palette.ecruWhite,
    "terminal.ansiYellow": palette.tacao,
    "terminal.background": palette.bunker,
    "terminal.foreground": palette.ecruWhite,
    "terminalCursor.background": palette.cuttySark,
    "terminalCursor.foreground": palette.cuttySark,
    "textBlockQuote.background": palette.heather,
    "textBlockQuote.border": palette.heather,
    "textCodeBlock.background": `${palette.heather}33`,
    "textLink.activeForeground": palette.bermudaGray,
    "textLink.foreground": palette.bermudaGray,
    "textPreformat.foreground": palette.bermudaGray,
    "textSeparator.foreground": palette.bermudaGray,
    "titleBar.activeBackground": palette.bunker,
    "titleBar.activeForeground": palette.ecruWhite,
    "titleBar.inactiveBackground": palette.ebonyClay,
    "titleBar.inactiveForeground": `${palette.ecruWhite}33`,
    "walkThrough.embeddedEditorBackground": palette.ebonyClay,
    "widget.shadow": `${palette.black}26`,
    //"activityBar.activeBorder": palette.ecruWhite,
    //"activityBar.dropBorder": palette.ecruWhite,
    //"activityBar.inactiveForeground": palette."#faf9f166",
    //"banner.background": palette.ebonyClay4,
    //"banner.foreground": palette.heather,
    //"banner.iconForeground": palette."#3794ff",
    //"breadcrumb.background": palette.ebonyClay,
    //"button.border": palette."#faf9f100",
    //"button.secondaryBackground": palette."#3a3d41",
    //"button.secondaryForeground": palette.ecruWhite,
    //"button.secondaryHoverBackground": palette."#45494e",
    //"charts.blue": palette."#3794ff",
    //"charts.foreground": palette.heather,
    //"charts.green": palette."#89d185",
    //"charts.lines": `${palette.heather}80`,
    //"charts.orange": palette."#d18616",
    //"charts.purple": palette."#b180d7",
    //"charts.red": palette.deepBlush,
    //"charts.yellow": palette.tacao,
    //"checkbox.background": palette.riverBed,
    //"checkbox.border": palette.riverBed,
    //"checkbox.foreground": palette.ecruWhite,
    //"commandCenter.activeBackground": palette."#5a5d5e50",
    //"commandCenter.activeForeground": palette.ecruWhite,
    //"commandCenter.border": palette.bunker,
    //"commandCenter.foreground": palette.ecruWhite,
    //"debugConsole.errorForeground": palette.deepBlush,
    //"debugConsole.infoForeground": palette."#3794ff",
    //"debugConsole.sourceForeground": palette.heather,
    //"debugConsole.warningForeground": palette.tacao,
    //"debugConsoleInputIcon.foreground": palette.heather,
    //"debugIcon.breakpointCurrentStackframeForeground": palette."#ffcc00",
    //"debugIcon.breakpointDisabledForeground": palette."#848484",
    //"debugIcon.breakpointForeground": palette."#e51400",
    //"debugIcon.breakpointStackframeForeground": palette."#89d185",
    //"debugIcon.breakpointUnverifiedForeground": palette."#848484",
    //"debugIcon.continueForeground": palette."#75beff",
    //"debugIcon.disconnectForeground": palette."#f48771",
    //"debugIcon.pauseForeground": palette."#75beff",
    //"debugIcon.restartForeground": palette."#89d185",
    //"debugIcon.startForeground": palette."#89d185",
    //"debugIcon.stepBackForeground": palette."#75beff",
    //"debugIcon.stepIntoForeground": palette."#75beff",
    //"debugIcon.stepOutForeground": palette."#75beff",
    //"debugIcon.stepOverForeground": palette."#75beff",

    //"debugTokenExpression.boolean": palette."#4e94ce",
    //"debugTokenExpression.error": palette."#f48771",
    //"debugTokenExpression.name": palette.viola,
    //"debugTokenExpression.number": palette.coriander,
    //"debugTokenExpression.string": palette.myPink,
    //"debugTokenExpression.value": palette."#cccccc99",
    //"debugView.exceptionLabelBackground": palette."#6c2022",
    //"debugView.exceptionLabelForeground": palette.heather,
    //"debugView.stateLabelBackground": palette."#88888844",
    //"debugView.stateLabelForeground": palette.heather,
    //"debugView.valueChangedHighlight": palette.havelockBlue,
    //"diffEditor.diagonalFill": `${palette.silver}33`,
    //"disabledForeground": palette."#cccccc80",
    //"editor.focusedStackFrameHighlightBackground": palette."#7abd7a4d",
    //"editor.foldBackground": palette."#3a454e4d",
    //"editor.inlineValuesBackground": palette."#ffc80033",
    //"editor.inlineValuesForeground": palette."#faf9f180",
    //"editor.linkedEditingBackground": palette."#ff00004d",
    //"editor.snippetFinalTabstopHighlightBorder": palette."#525252",
    //"editor.snippetTabstopHighlightBackground": palette."#7c7c7c4d",
    //"editor.stackFrameHighlightBackground": palette."#ffff0033",
    //"editor.symbolHighlightBackground": `${palette.heather}30`,
    //"editorActiveLineNumber.foreground": palette."#c6c6c6",

    // "editorBracketHighlight.foreground4": palette."#00000000",
    // "editorBracketHighlight.foreground5": palette."#00000000",
    // "editorBracketHighlight.foreground6": palette."#00000000"
    //"editorBracketHighlight.unexpectedBracket.foreground": palette."#ff1212cc",
    //"editorBracketPairGuide.activeBackground1": palette."#00000000",
    //"editorBracketPairGuide.activeBackground2": palette."#00000000",
    //"editorBracketPairGuide.activeBackground3": palette."#00000000",
    //"editorBracketPairGuide.activeBackground4": palette."#00000000",
    //"editorBracketPairGuide.activeBackground5": palette."#00000000",
    //"editorBracketPairGuide.activeBackground6": palette."#00000000",
    //"editorBracketPairGuide.background1": palette."#00000000",
    //"editorBracketPairGuide.background2": palette."#00000000",
    //"editorBracketPairGuide.background3": palette."#00000000",
    //"editorBracketPairGuide.background4": palette."#00000000",
    //"editorBracketPairGuide.background5": palette."#00000000",
    //"editorBracketPairGuide.background6": palette."#00000000",
    //"editorCommentsWidget.rangeActiveBackground": palette."#333f4a1a",
    //"editorCommentsWidget.rangeActiveBorder": palette."#333f4a66",
    //"editorCommentsWidget.rangeBackground": palette."#333f4a1a",
    //"editorCommentsWidget.rangeBorder": palette."#333f4a66",
    //"editorCommentsWidget.resolvedBorder": palette."#cccccc80",
    //"editorCommentsWidget.unresolvedBorder": palette.limedSpruce,
    //"editorGhostText.foreground": palette."#faf9f156",
    //"editorGroup.dropIntoPromptBackground": palette.mirage2,
    //"editorGroup.dropIntoPromptForeground": palette.heather,
    //"editorGutter.commentRangeForeground": palette."#c5c5c5",
    //"editorGutter.foldingControlForeground": palette."#c5c5c5",
    //"editorHint.foreground": palette."#eeeeeeb3",
    //"editorHoverWidget.foreground": palette.heather,
    //"editorHoverWidget.highlightForeground": palette.mineralGreen,
    //"editorHoverWidget.statusBarBackground": palette."#192a36",
    //"editorInfo.foreground": palette."#3794ff",
    //"editorInlayHint.background": palette."#5ec4ff99",
    //"editorInlayHint.foreground": palette."#181e24cc",
    //"editorInlayHint.parameterBackground": palette."#5ec4ff99",
    //"editorInlayHint.parameterForeground": palette."#181e24cc",
    //"editorInlayHint.typeBackground": palette."#5ec4ff99",
    //"editorInlayHint.typeForeground": palette."#181e24cc",
    //"editorLightBulb.foreground": palette."#ffcc00",
    //"editorLightBulbAutoFix.foreground": palette."#75beff",
    //"editorLineNumber.activeForeground": palette."#c6c6c6",
    //"editorMarkerNavigationError.headerBackground": palette."#d954681a",
    //"editorMarkerNavigationInfo.background": palette."#3794ff",
    //"editorMarkerNavigationInfo.headerBackground": palette."#3794ff1a",
    //"editorMarkerNavigationWarning.headerBackground": palette."#d98e481a",
    //"editorOverviewRuler.addedForeground": palette."#8bd49c99",
    //"editorOverviewRuler.bracketMatchForeground": palette."#a0a0a0",
    //"editorOverviewRuler.deletedForeground": palette."#e27e8d99",
    //"editorOverviewRuler.errorForeground": palette."#ff1212b3",
    //"editorOverviewRuler.findMatchForeground": palette."#d186167e",
    //"editorOverviewRuler.infoForeground": palette."#3794ff",
    //"editorOverviewRuler.modifiedForeground": palette."#26506d99",
    //"editorOverviewRuler.rangeHighlightForeground": palette."#007acc99",
    //"editorOverviewRuler.selectionHighlightForeground": palette."#a0a0a0cc",
    //"editorOverviewRuler.warningForeground": palette.tacao,
    //"editorOverviewRuler.wordHighlightForeground": palette."#a0a0a0cc",
    //"editorOverviewRuler.wordHighlightStrongForeground": palette."#c0a0c0cc",
    //"editorPane.background": palette.ebonyClay,
    //"editorSuggestWidget.focusHighlightForeground": palette.mineralGreen,
    //"editorSuggestWidget.selectedForeground": palette.heather,
    //"editorSuggestWidget.selectedIconForeground": palette.ecruWhite,
    //"editorSuggestWidgetStatus.foreground": `${palette.heather}80`,
    //"editorUnicodeHighlight.background": palette."#bd9b0326",
    //"editorUnicodeHighlight.border": palette."#bd9b03",
    //"editorUnnecessaryCode.opacity": palette."#000000aa",
    //"editorWidget.foreground": palette.heather,
    //"extensionBadge.remoteBackground": palette.heather,
    //"extensionBadge.remoteForeground": palette.mirage,
    //"extensionIcon.preReleaseForeground": palette."#1d9271",
    //"extensionIcon.sponsorForeground": palette."#d758b3",
    //"extensionIcon.starForeground": palette."#ff8e00",
    //"extensionIcon.verifiedForeground": palette.bermudaGray,
    //"gitDecoration.renamedResourceForeground": palette."#73c991",
    //"gitDecoration.stageDeletedResourceForeground": palette."#c74e39",
    //"gitDecoration.stageModifiedResourceForeground": palette."#e2c08d",
    //"gitDecoration.submoduleResourceForeground": palette."#8db9e2",
    //"icon.foreground": palette."#c5c5c5",
    //"inputOption.activeBackground": palette."#333f4a66",
    //"inputOption.activeForeground": palette.ecruWhite,
    //"inputOption.hoverBackground": palette."#5a5d5e80",
    //"interactive.activeCodeBorder": palette.limedSpruce,
    //"interactive.inactiveCodeBorder": palette.limedSpruce,
    //"keybindingLabel.background": palette."#8080802b",
    //"keybindingLabel.border": palette."#33333399",
    //"keybindingLabel.bottomBorder": palette."#44444499",
    //"keybindingLabel.foreground": palette."#cccccc",
    //"keybindingTable.headerBackground": palette."#b7c5d30a",
    //"keybindingTable.rowsBackground": palette."#b7c5d30a",
    //"list.deemphasizedForeground": palette."#8c8c8c",
    //"list.errorForeground": palette."#f88070",
    //"list.filterMatchBackground": `${palette.heather}30`,
    //"list.focusHighlightForeground": palette.mineralGreen,
    //"list.focusOutline": palette.limedSpruce,
    //"list.invalidItemForeground": palette."#b89500",
    //"list.warningForeground": palette."#cca700",
    //"listFilterWidget.background": palette."#653723",
    //"listFilterWidget.noMatchesOutline": palette."#be1100",
    //"listFilterWidget.outline": palette."#00000000",
    //"menu.selectionBackground": palette.ebonyClay4,
    //"menu.selectionForeground": palette.heather,
    //"menu.separatorBackground": palette."#606060",
    //"menubar.selectionBackground": palette."#5a5d5e50",
    //"menubar.selectionForeground": palette.ecruWhite,
    //"merge.commonContentBackground": palette."#60606029",
    //"merge.commonHeaderBackground": palette."#60606066",
    //"merge.currentContentBackground": palette."#40c8ae33",
    //"merge.currentHeaderBackground": palette."#40c8ae80",
    //"merge.incomingContentBackground": palette."#40a6ff33",
    //"merge.incomingHeaderBackground": palette."#40a6ff80",
    //"mergeEditor.change.background": palette."#9bb95533",
    //"mergeEditor.change.word.background": palette."#9bb9551e",
    //"mergeEditor.conflict.handled.minimapOverViewRuler": palette."#adaca8ee",
    //"mergeEditor.conflict.handledFocused.border": palette."#c1c1c1cc",
    //"mergeEditor.conflict.handledUnfocused.border": palette."#86868649",
    //"mergeEditor.conflict.unhandled.minimapOverViewRuler": palette."#fcba03",
    //"mergeEditor.conflict.unhandledFocused.border": palette."#ffa600",
    //"mergeEditor.conflict.unhandledUnfocused.border": palette."#ffa6007a",

    //"notebook.cellBorderColor": palette.limedSpruce,
    //"notebook.cellEditorBackground": palette.bunker,
    //"notebook.cellInsertionIndicator": palette.limedSpruce,
    //"notebook.cellStatusBarItemHoverBackground": palette."#faf9f126",
    //"notebook.cellToolbarSeparator": palette."#80808059",
    //"notebook.editorBackground": palette.ebonyClay,
    //"notebook.focusedCellBorder": palette.limedSpruce,
    //"notebook.focusedEditorBorder": palette.limedSpruce,
    //"notebook.inactiveFocusedCellBorder": palette.limedSpruce,
    //"notebook.selectedCellBackground": palette.limedSpruce,
    //"notebook.selectedCellBorder": palette.limedSpruce,
    //"notebook.symbolHighlightBackground": palette."#faf9f10b",
    //"notebookScrollbarSlider.activeBackground": palette.limedSpruce,
    //"notebookScrollbarSlider.background": `${palette.riverBed}80`,
    //"notebookScrollbarSlider.hoverBackground": palette."#41505ecc",
    //"notebookStatusErrorIcon.foreground": palette.deepBlush,
    //"notebookStatusRunningIcon.foreground": palette.heather,
    //"notebookStatusSuccessIcon.foreground": palette."#89d185",

    //"panel.dropBorder": palette.riverBed,
    //"panelSection.border": palette.bunker,
    //"panelSection.dropBackground": palette.limedSpruce,
    //"panelSectionHeader.background": palette."#80808033",
    //"panelSectionHeader.border": palette."#faf9f100",
    //"problemsErrorIcon.foreground": palette.deepBlush,
    //"problemsInfoIcon.foreground": palette."#3794ff",
    //"problemsWarningIcon.foreground": palette.tacao,
    //"quickInput.background": palette.mirage2,
    //"quickInput.foreground": palette.heather,
    //"quickInputList.focusBackground": palette.ebonyClay4,
    //"quickInputList.focusForeground": palette.heather,
    //"quickInputList.focusIconForeground": palette.ecruWhite,
    //"quickInputTitle.background": palette."#faf9f11b",
    //"sash.hoverBorder": palette.limedSpruce,
    //"scm.providerBorder": palette."#454545",
    //"searchEditor.findMatchBackground": palette."#b7c5d320",
    //"searchEditor.textInputBorder": palette.limedSpruce,
    //"settings.checkboxBackground": palette.riverBed,
    //"settings.checkboxBorder": palette.riverBed,
    //"settings.checkboxForeground": palette.ecruWhite,
    //"settings.dropdownBackground": palette.riverBed,
    //"settings.dropdownBorder": palette.riverBed,
    //"settings.dropdownForeground": palette.ecruWhite,
    //"settings.dropdownListBorder": palette.limedSpruce,
    //"settings.focusedRowBackground": palette."#1d252c99",
    //"settings.focusedRowBorder": palette."#faf9f11f",
    //"settings.headerBorder": palette.bunker,
    //"settings.headerForeground": palette."#e7e7e7",
    //"settings.modifiedItemIndicator": palette."#0c7d9d",
    //"settings.numberInputBackground": palette.limedSpruce,
    //"settings.numberInputBorder": palette.limedSpruce,
    //"settings.numberInputForeground": palette.heather,
    //"settings.rowHoverBackground": palette."#1d252c4d",
    //"settings.sashBorder": palette.bunker,
    //"settings.textInputBackground": palette.limedSpruce,
    //"settings.textInputBorder": palette.limedSpruce,
    //"settings.textInputForeground": palette.heather,
    //"sideBar.dropBackground": palette.limedSpruce,
    //"sideBySideEditor.horizontalBorder": palette.ebonyClay,
    //"sideBySideEditor.verticalBorder": palette.ebonyClay,
    //"statusBar.debuggingBorder": palette.ebonyClay,
    //"statusBar.focusBorder": palette.heather,
    //"statusBar.noFolderBorder": palette.ebonyClay,
    //"statusBarItem.compactHoverBackground": `${palette.ecruWhite}33`,
    //"statusBarItem.errorBackground": palette."#ac273b",
    //"statusBarItem.errorForeground": palette.ecruWhite,
    //"statusBarItem.focusBorder": palette.heather,
    //"statusBarItem.prominentForeground": palette.heather,
    //"statusBarItem.warningBackground": palette."#bd7b1f",
    //"statusBarItem.warningForeground": palette.ecruWhite,
    //"symbolIcon.arrayForeground": palette.heather,
    //"symbolIcon.booleanForeground": palette.heather,
    //"symbolIcon.classForeground": palette."#ee9d28",
    //"symbolIcon.colorForeground": palette.heather,
    //"symbolIcon.constantForeground": palette.heather,
    //"symbolIcon.constructorForeground": palette."#b180d7",
    //"symbolIcon.enumeratorForeground": palette."#ee9d28",
    //"symbolIcon.enumeratorMemberForeground": palette."#75beff",
    //"symbolIcon.eventForeground": palette."#ee9d28",
    //"symbolIcon.fieldForeground": palette."#75beff",
    //"symbolIcon.fileForeground": palette.heather,
    //"symbolIcon.folderForeground": palette.heather,
    //"symbolIcon.functionForeground": palette."#b180d7",
    //"symbolIcon.interfaceForeground": palette."#75beff",
    //"symbolIcon.keyForeground": palette.heather,
    //"symbolIcon.keywordForeground": palette.heather,
    //"symbolIcon.methodForeground": palette."#b180d7",
    //"symbolIcon.moduleForeground": palette.heather,
    //"symbolIcon.namespaceForeground": palette.heather,
    //"symbolIcon.nullForeground": palette.heather,
    //"symbolIcon.numberForeground": palette.heather,
    //"symbolIcon.objectForeground": palette.heather,
    //"symbolIcon.operatorForeground": palette.heather,
    //"symbolIcon.packageForeground": palette.heather,
    //"symbolIcon.propertyForeground": palette.heather,
    //"symbolIcon.referenceForeground": palette.heather,
    //"symbolIcon.snippetForeground": palette.heather,
    //"symbolIcon.stringForeground": palette.heather,
    //"symbolIcon.structForeground": palette.heather,
    //"symbolIcon.textForeground": palette.heather,
    //"symbolIcon.typeParameterForeground": palette.heather,
    //"symbolIcon.unitForeground": palette.heather,
    //"symbolIcon.variableForeground": palette."#75beff",
    //"tab.activeModifiedBorder": palette."#3399cc",
    //"tab.inactiveModifiedBorder": palette."#3399cc80",
    //"tab.unfocusedActiveBackground": palette.ebonyClay,
    //"tab.unfocusedActiveBorder": palette."#1d252c80",
    //"tab.unfocusedActiveModifiedBorder": palette."#3399cc80",
    //"tab.unfocusedInactiveBackground": palette.bunker,
    //"tab.unfocusedInactiveModifiedBorder": palette."#3399cc40",
    //"terminal.border": palette.bunker,
    //"terminal.dropBackground": palette.limedSpruce,
    //"terminal.findMatchBackground": `${palette.heather}80`,
    //"terminal.findMatchHighlightBackground": `${palette.heather}30`,
    //"terminal.selectionBackground": palette."#3a454e",
    //"terminal.tab.activeBorder": palette.ebonyClay,
    //"terminalCommandDecoration.defaultBackground": palette."#faf9f140",
    //"terminalCommandDecoration.errorBackground": palette."#f14c4c",
    //"terminalCommandDecoration.successBackground": palette."#1b81a8",
    //"terminalOverviewRuler.cursorForeground": palette."#a0a0a0cc",
    //"terminalOverviewRuler.findMatchForeground": palette."#d186167e",
    //"testing.iconErrored": palette."#f14c4c",
    //"testing.iconFailed": palette."#f14c4c",
    //"testing.iconPassed": palette."#73c991",
    //"testing.iconQueued": palette."#cca700",
    //"testing.iconSkipped": palette."#848484",
    //"testing.iconUnset": palette."#848484",
    //"testing.message.error.decorationForeground": palette.deepBlush,
    //"testing.message.error.lineBackground": palette."#ff000033",
    //"testing.message.info.decorationForeground": `${palette.heather}80`,
    //"testing.peekBorder": palette.deepBlush,
    //"testing.peekHeaderBackground": palette."#e27e8d1a",
    //"testing.runAction": palette."#73c991",
    //"toolbar.activeBackground": palette."#63666750",
    //"toolbar.hoverBackground": palette."#5a5d5e50",
    //"tree.indentGuidesStroke": palette."#585858",
    //"tree.tableColumnsBorder": palette."#cccccc20",
    //"tree.tableOddRowsBackground": palette."#b7c5d30a",
    //"welcomePage.progress.background": palette.limedSpruce,
    //"welcomePage.progress.foreground": palette.bermudaGray,
    //"welcomePage.tileBackground": palette.mirage2,
    //"welcomePage.tileHoverBackground": palette."#192a36",
    //"welcomePage.tileShadow": palette."#00000026",
    //"activityBar.activeBackground": palette.null,
    //"activityBar.activeFocusBorder": palette.null,
    //"commandCenter.background": palette.null,
    //"contrastActiveBorder": palette.null,
    //"diffEditor.border": palette.null,
    //"diffEditor.insertedLineBackground": palette.null,
    //"diffEditor.removedLineBackground": palette.null,
    //"diffEditorGutter.insertedLineBackground": palette.null,
    //"diffEditorGutter.removedLineBackground": palette.null,
    //"diffEditorOverview.insertedForeground": palette.null,
    //"diffEditorOverview.removedForeground": palette.null,
    //"dropdown.listBackground": palette.null,
    //"editor.findMatchBorder": palette.null,
    //"editor.findMatchHighlightBorder": palette.null,
    //"editor.findRangeHighlightBorder": palette.null,
    //"editor.rangeHighlightBorder": palette.null,
    //"editor.selectionForeground": palette.null,
    //"editor.selectionHighlightBorder": palette.null,
    //"editor.snippetFinalTabstopHighlightBackground": palette.null,
    //"editor.snippetTabstopHighlightBorder": palette.null,
    //"editor.symbolHighlightBorder": palette.null,
    //"editor.wordHighlightBorder": palette.null,
    //"editor.wordHighlightStrongBorder": palette.null,
    //"editorCursor.background": palette.null,
    //"editorError.background": palette.null,
    //"editorGhostText.background": palette.null,
    //"editorGhostText.border": palette.null,
    //"editorGroup.dropIntoPromptBorder": palette.null,
    //"editorGroup.focusedEmptyBorder": palette.null,
    //"editorGroupHeader.border": palette.null,
    //"editorHint.border": palette.null,
    //"editorInfo.background": palette.null,
    //"editorInfo.border": palette.null,
    //"editorOverviewRuler.background": palette.null,
    //"editorUnnecessaryCode.border": palette.null,
    //"editorWarning.background": palette.null,
    //"editorWidget.resizeBorder": palette.null,
    //"inputValidation.infoForeground": palette.null,
    //"list.filterMatchBorder": palette.null,
    //"list.focusAndSelectionOutline": palette.null,
    //"list.inactiveFocusBackground": palette.null,
    //"list.inactiveFocusOutline": palette.null,
    //"list.inactiveSelectionIconForeground": palette.null,
    //"menu.border": palette.null,
    //"menu.selectionBorder": palette.null,
    //"menubar.selectionBorder": palette.null,
    //"merge.border": palette.null,
    //"minimap.background": palette.null,
    //"notebook.cellHoverBackground": palette.null,
    //"notebook.focusedCellBackground": palette.null,
    //"notebook.inactiveSelectedCellBorder": palette.null,
    //"notebook.outputContainerBackgroundColor": palette.null,
    //"notebook.outputContainerBorderColor": palette.null,
    //"notificationCenter.border": palette.null,
    //"notificationCenterHeader.foreground": palette.null,
    //"notificationToast.border": palette.null,
    //"panelInput.border": palette.null,
    //"panelSectionHeader.foreground": palette.null,
    //"peekViewEditor.matchHighlightBorder": palette.null,
    //"quickInput.list.focusBackground": palette.null,
    //"searchEditor.findMatchBorder": palette.null,
    //"statusBarItem.settingsProfilesBackground": palette.null,
    //"statusBarItem.settingsProfilesForeground": palette.null,
    //"tab.activeBorderTop": palette.null,
    //"tab.hoverBackground": palette.null,
    //"tab.hoverBorder": palette.null,
    //"tab.hoverForeground": palette.null,
    //"tab.unfocusedActiveBorderTop": palette.null,
    //"tab.unfocusedHoverBackground": palette.null,
    //"tab.unfocusedHoverBorder": palette.null,
    //"tab.unfocusedHoverForeground": palette.null,
    //"terminal.findMatchBorder": palette.null,
    //"terminal.findMatchHighlightBorder": palette.null,
    //"terminal.selectionForeground": palette.null,
    //"testing.message.info.lineBackground": palette.null,
    //"titleBar.border": palette.null,
    //"toolbar.hoverOutline": palette.null,
    //"welcomePage.background": palette.null,
    //"window.activeBorder": palette.null,
    //"window.inactiveBorder": palette.null
  },
  tokenColors: [
    {
      scope: ["meta.embedded", "source.groovy.embedded"],
      settings: {
        foreground: palette.alto,
      },
    },
    {
      scope: "emphasis",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "strong",
      settings: {
        fontStyle: "bold",
      },
    },
    {
      scope: "header",
      settings: {
        foreground: palette.navyBlue,
      },
    },
    {
      scope: "comment",
      settings: {
        foreground: palette.fernGreen,
      },
    },
    {
      scope: "constant.language",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: [
        "constant.numeric",
        "variable.other.enummember",
        "keyword.operator.plus.exponent",
        "keyword.operator.minus.exponent",
      ],
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      scope: "constant.regexp",
      settings: {
        foreground: palette.kimberly,
      },
    },
    {
      scope: "entity.name.tag",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "entity.name.tag.css",
      settings: {
        foreground: palette.straw,
      },
    },
    {
      scope: "entity.other.attribute-name",
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: [
        "entity.other.attribute-name.class.css",
        "entity.other.attribute-name.class.mixin.css",
        "entity.other.attribute-name.id.css",
        "entity.other.attribute-name.parent-selector.css",
        "entity.other.attribute-name.pseudo-class.css",
        "entity.other.attribute-name.pseudo-element.css",
        "source.css.less entity.other.attribute-name.id",
        "entity.other.attribute-name.scss",
      ],
      settings: {
        foreground: palette.straw,
      },
    },
    {
      scope: "invalid",
      settings: {
        foreground: palette.deepBlush,
      },
    },
    {
      scope: "markup.underline",
      settings: {
        fontStyle: "underline",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        foreground: palette.havelockBlue,
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.heading",
      settings: {
        foreground: palette.havelockBlue,
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.strikethrough",
      settings: {
        fontStyle: "strikethrough",
      },
    },
    {
      scope: "markup.inserted",
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      name: "Deleted line markup",
      scope: "markup.deleted",
      settings: {
        foreground: palette.deepBlush,
      },
    },
    {
      name: "Changed line markup",
      scope: "markup.changed",
      settings: {
        foreground: palette.tacao,
      },
    },
    {
      scope: "punctuation.terminator.statement",
      settings: {
        foreground: `${palette.heather}b4`,
      },
    },
    {
      scope: "punctuation.definition.quote.begin.markdown",
      settings: {
        foreground: palette.chaletGreen,
      },
    },
    {
      scope: "punctuation.definition.list.begin.markdown",
      settings: {
        foreground: palette.cornflowerBlue,
      },
    },
    {
      scope: "markup.inline.raw",
      settings: {
        foreground: `${palette.myPink}ec`,
      },
    },
    {
      scope: "punctuation.definition.tag",
      settings: {
        foreground: palette.gray,
      },
    },
    {
      scope: ["meta.preprocessor", "entity.name.function.preprocessor"],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "meta.preprocessor.string",
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: "meta.preprocessor.numeric",
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      scope: "meta.structure.dictionary.key.python",
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: "meta.diff.header",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "storage",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "storage.type",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: ["storage.modifier", "keyword.operator.noexcept"],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: ["string", "meta.embedded.assembly"],
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: "string.tag",
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: "string.value",
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: "string.regexp",
      settings: {
        foreground: palette.chestnutRose,
      },
    },
    {
      scope: [
        "punctuation.definition.template-expression.begin",
        "punctuation.definition.template-expression.end",
        "punctuation.section.embedded",
      ],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: ["meta.template.expression"],
      settings: {
        foreground: palette.alto,
      },
    },
    {
      scope: [
        "support.type.vendored.property-name",
        "support.type.property-name",
        "variable.css",
        "variable.scss",
        "variable.other.less",
        "source.coffee.embedded",
      ],
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: "keyword",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "keyword.control",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "keyword.operator",
      settings: {
        foreground: palette.alto,
      },
    },
    {
      scope: [
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.cast",
        "keyword.operator.sizeof",
        "keyword.operator.alignof",
        "keyword.operator.typeid",
        "keyword.operator.alignas",
        "keyword.operator.instanceof",
        "keyword.operator.logical.python",
        "keyword.operator.wordlike",
      ],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "keyword.other.unit",
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      scope: [
        "punctuation.section.embedded.begin.php",
        "punctuation.section.embedded.end.php",
      ],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "support.function.git-rebase",
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: "constant.sha.git-rebase",
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      scope: [
        "storage.modifier.import.java",
        "variable.language.wildcard.java",
        "storage.modifier.package.java",
      ],
      settings: {
        foreground: palette.alto,
      },
    },
    {
      scope: "variable.language",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: [
        "entity.name.function",
        "support.function",
        "support.constant.handlebars",
        "source.powershell variable.other.member",
        "entity.name.operator.custom-literal",
      ],
      settings: {
        foreground: palette.sapling,
      },
    },
    {
      scope: [
        "support.class",
        "support.type",
        "entity.name.type",
        "entity.name.namespace",
        "entity.other.attribute",
        "entity.name.scope-resolution",
        "entity.name.class",
        "storage.type.numeric.go",
        "storage.type.byte.go",
        "storage.type.boolean.go",
        "storage.type.string.go",
        "storage.type.uintptr.go",
        "storage.type.error.go",
        "storage.type.rune.go",
        "storage.type.cs",
        "storage.type.generic.cs",
        "storage.type.modifier.cs",
        "storage.type.variable.cs",
        "storage.type.annotation.java",
        "storage.type.generic.java",
        "storage.type.java",
        "storage.type.object.array.java",
        "storage.type.primitive.array.java",
        "storage.type.primitive.java",
        "storage.type.token.java",
        "storage.type.groovy",
        "storage.type.annotation.groovy",
        "storage.type.parameters.groovy",
        "storage.type.generic.groovy",
        "storage.type.object.array.groovy",
        "storage.type.primitive.array.groovy",
        "storage.type.primitive.groovy",
      ],
      settings: {
        foreground: palette.puertoRico,
      },
    },
    {
      scope: [
        "meta.type.cast.expr",
        "meta.type.new.expr",
        "support.constant.math",
        "support.constant.dom",
        "support.constant.json",
        "entity.other.inherited-class",
      ],
      settings: {
        foreground: palette.puertoRico,
      },
    },
    {
      scope: [
        "keyword.control",
        "source.cpp keyword.operator.new",
        "keyword.operator.delete",
        "keyword.other.using",
        "keyword.other.operator",
        "entity.name.operator",
      ],
      settings: {
        foreground: palette.viola,
      },
    },
    {
      scope: [
        "variable",
        "meta.definition.variable.name",
        "support.variable",
        "entity.name.variable",
        "constant.other.placeholder",
      ],
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: ["variable.other.constant", "variable.other.enummember"],
      settings: {
        foreground: palette.malibu,
      },
    },
    {
      scope: ["meta.object-literal.key"],
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: [
        "punctuation.separator.key-value",
        "keyword.operator.type.annotation",
      ],
      settings: {
        foreground: `${palette.anakiwa}c0`,
      },
    },
    {
      scope: [
        "support.constant.property-value",
        "support.constant.font-name",
        "support.constant.media-type",
        "support.constant.media",
        "constant.other.color.rgb-value",
        "constant.other.rgb-value",
        "support.constant.color",
      ],
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: [
        "punctuation.definition.group.regexp",
        "punctuation.definition.group.assertion.regexp",
        "punctuation.definition.character-class.regexp",
        "punctuation.character.set.begin.regexp",
        "punctuation.character.set.end.regexp",
        "keyword.operator.negation.regexp",
        "support.other.parenthesis.regexp",
      ],
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: [
        "constant.character.character-class.regexp",
        "constant.other.character-class.set.regexp",
        "constant.other.character-class.regexp",
        "constant.character.set.regexp",
      ],
      settings: {
        foreground: palette.chestnutRose,
      },
    },
    {
      scope: [
        "keyword.control.import",
        "keyword.control.export",
        "keyword.control.from",
      ],
      settings: {
        foreground: `${palette.viola}b0`,
      },
    },
    {
      scope: ["keyword.operator.or.regexp", "keyword.control.anchor.regexp"],
      settings: {
        foreground: palette.sapling,
      },
    },
    {
      scope: "keyword.operator.quantifier.regexp",
      settings: {
        foreground: palette.straw,
      },
    },
    {
      scope: "constant.character",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "constant.character.escape",
      settings: {
        foreground: palette.straw,
      },
    },
    {
      scope: "entity.name.label",
      settings: {
        foreground: palette.silver,
      },
    },
    {
      scope: "token.info-token",
      settings: {
        foreground: palette.cornflowerBlue,
      },
    },
    {
      scope: "token.warn-token",
      settings: {
        foreground: palette.hokeyPokey,
      },
    },
    {
      scope: "token.error-token",
      settings: {
        foreground: palette.deepBlush,
      },
    },
    {
      scope: "token.debug-token",
      settings: {
        foreground: palette.mediumPurlple,
      },
    },
    {
      name: "Inserted line markup",
      scope: "markup.inserted",
      settings: {
        foreground: palette.vistaBlue,
      },
    },
    {
      name: "Deleted line markup",
      scope: "markup.deleted",
      settings: {
        foreground: palette.deepBlush,
      },
    },
    {
      name: "Changed line markup",
      scope: "markup.changed",
      settings: {
        foreground: palette.tacao,
      },
    },
  ],
}
