import { palette } from "./palette.js"

export const cozyDark = {
  $schema: "vscode://schemas/color-theme",
  type: "dark",
  colors: {
    "activityBar.background": palette.ebonyClay,
    "activityBar.border": palette.limedSpruce,
    "activityBar.foreground": palette.ecruWhite,
    "activityBarBadge.background": palette.mineralGreen,
    "activityBarBadge.foreground": `${palette.ecruWhite}99`,
    "badge.background": palette.mineralGreen,
    "badge.foreground": palette.ecruWhite,
    "breadcrumb.activeSelectionForeground": palette.riverBed,
    "breadcrumb.focusForeground": palette.heather,
    "breadcrumb.foreground": palette.bermudaGray,
    "breadcrumbPicker.background": palette.outerSpace,
    "button.background": palette.ebonyClay,
    "button.foreground": palette.heather,
    "button.hoverBackground": palette.mineralGreen,
    contrastBorder: `${palette.ecruWhite}00`,
    "debugExceptionWidget.background": palette.ebonyClay,
    "debugExceptionWidget.border": palette.heather,
    "debugIcon.stopForeground": palette.deepBlush,
    "debugToolBar.background": palette.ebonyClay,
    descriptionForeground: palette.heather,
    "diffEditor.insertedTextBackground": palette.mineralGreen2,
    "diffEditor.insertedTextBorder": palette.limedSpruce,
    "diffEditor.removedTextBackground": palette.donJuan,
    "diffEditor.removedTextBorder": palette.limedSpruce,
    "dropdown.background": palette.riverBed,
    "dropdown.border": palette.riverBed,
    "dropdown.foreground": palette.ecruWhite,
    "editor.background": palette.ebonyClay,
    "editor.findMatchBackground": `${palette.heather}80`,
    "editor.findMatchHighlightBackground": `${palette.heather}30`,
    "editor.findRangeHighlightBackground": palette.blueDianne,
    "editor.foreground": palette.heather,
    "editor.hoverHighlightBackground": palette.limedSpruce,
    "editor.inactiveSelectionBackground": palette.ebonyClay2,
    "editor.lineHighlightBackground": palette.ebonyClay3,
    "editor.lineHighlightBorder": palette.ebonyClay3,
    "editor.rangeHighlightBackground": palette.ebonyClay3,
    "editor.selectionBackground": palette.limedSpruce2,
    "editor.selectionHighlightBackground": palette.ebonyClay3,
    "editor.wordHighlightBackground": palette.mako,
    "editor.wordHighlightStrongBackground": palette.riverBed,
    "editorBracketMatch.background": palette.kashmirBlue,
    "editorBracketMatch.border": palette.astronaut,
    "editorBracketHighlight.foreground1": palette.tacao,
    "editorBracketHighlight.foreground2": palette.tapestry,
    "editorBracketHighlight.foreground3": palette.dodgerBlue,
    "editorCodeLens.foreground": palette.heather,
    "editorCursor.foreground": palette.heather,
    "editorError.border": palette.limedSpruce,
    "editorError.foreground": palette.deepBlush,
    "editorGroup.border": palette.ebonyClay,
    "editorGroup.dropBackground": palette.limedSpruce,
    "editorGroup.emptyBackground": palette.ebonyClay,
    "editorGroupHeader.noTabsBackground": palette.limedSpruce,
    "editorGroupHeader.tabsBackground": palette.mirage,
    "editorGroupHeader.tabsBorder": palette.limedSpruce,
    "editorGutter.addedBackground": palette.vistaBlue,
    "editorGutter.background": palette.ebonyClay,
    "editorGutter.deletedBackground": palette.deepBlush,
    "editorGutter.modifiedBackground": palette.astronaut,
    "editorHoverWidget.background": palette.mirage2,
    "editorHoverWidget.border": palette.limedSpruce,
    "editorIndentGuide.activeBackground": palette.doveGray,
    "editorIndentGuide.background": palette.outerSpace,
    "editorLineNumber.foreground": palette.riverBed,
    "editorLink.activeForeground": palette.heather,
    "editorMarkerNavigation.background": palette.ebonyClay,
    "editorMarkerNavigationError.background": palette.cabaret,
    "editorMarkerNavigationWarning.background": palette.rawSienna,
    "editorOverviewRuler.border": palette.limedSpruce,
    "editorOverviewRuler.commonContentForeground": `${palette.tacao}55`,
    "editorOverviewRuler.currentContentForeground": `${palette.amaranth}55`,
    "editorOverviewRuler.incomingContentForeground": `${palette.harlequin}55`,
    "editorRuler.foreground": palette.cello,
    "editorSuggestWidget.background": palette.mirage2,
    "editorSuggestWidget.border": palette.mirage2,
    "editorSuggestWidget.foreground": palette.heather,
    "editorSuggestWidget.highlightForeground": palette.tacao,
    "editorSuggestWidget.selectedBackground": palette.outerSpace,
    "editorWarning.border": `${palette.ecruWhite}00`,
    "editorWarning.foreground": palette.tacao,
    "editorWhitespace.foreground": `${palette.ecruWhite}1a`,
    "editorWidget.background": palette.mirage2,
    "editorWidget.border": palette.limedSpruce,
    errorForeground: palette.deepBlush,
    "extensionButton.prominentBackground": palette.mineralGreen,
    "extensionButton.prominentForeground": palette.ecruWhite,
    "extensionButton.prominentHoverBackground": palette.mineralGreen,
    focusBorder: palette.limedSpruce,
    foreground: palette.heather,
    "gitDecoration.addedResourceForeground": palette.aquaForest,
    "gitDecoration.conflictingResourceForeground": palette.scooter,
    "gitDecoration.deletedResourceForeground": palette.deepBlush,
    "gitDecoration.ignoredResourceForeground": palette.riverBed,
    "gitDecoration.modifiedResourceForeground": palette.tacao,
    "gitDecoration.untrackedResourceForeground": palette.vistaBlue,
    "input.background": palette.limedSpruce,
    "input.border": palette.limedSpruce,
    "input.foreground": palette.heather,
    "input.placeholderForeground": palette.heather,
    "inputOption.activeBorder": palette.dodgerBlue2,
    "inputValidation.errorBackground": palette.deepBlush,
    "inputValidation.errorBorder": palette.cabaret,
    "inputValidation.errorForeground": palette.ecruWhite,
    "inputValidation.infoBackground": palette.malibu,
    "inputValidation.infoBorder": palette.dodgerBlue2,
    "inputValidation.warningBackground": palette.tacao,
    "inputValidation.warningBorder": palette.rawSienna,
    "inputValidation.warningForeground": palette.ebonyClay4,
    "list.activeSelectionBackground": palette.ebonyClay4,
    "list.activeSelectionForeground": palette.heather,
    "list.activeSelectionIconForeground": palette.ecruWhite,
    "list.dropBackground": palette.limedSpruce,
    "list.focusBackground": palette.limedSpruce,
    "list.focusForeground": palette.heather,
    "list.highlightForeground": palette.cuttySark,
    "list.hoverBackground": palette.ebonyClay4,
    "list.hoverForeground": palette.heather,
    "list.inactiveSelectionBackground": palette.limedSpruce,
    "list.inactiveSelectionForeground": palette.heather,
    "menu.background": palette.shark,
    "menu.foreground": palette.silver,
    "minimap.errorHighlight": palette.deepBlush,
    "minimap.selectionHighlight": palette.cuttySark,
    "minimap.warningHighlight": palette.rawSienna,
    "minimapGutter.addedBackground": palette.vistaBlue,
    "minimapGutter.deletedBackground": palette.deepBlush,
    "minimapSlider.background": `${palette.mineralGreen}40`,
    "minimapSlider.hoverBackground": `${palette.mineralGreen}66`,
    "notificationCenterHeader.background": palette.gableGreen,
    "notificationLink.foreground": palette.bermudaGray,
    "notifications.background": palette.mirage2,
    "notifications.border": palette.gableGreen,
    "notifications.foreground": palette.heather,
    "notificationsErrorIcon.foreground": palette.deepBlush,
    "notificationsInfoIcon.foreground": palette.heather,
    "notificationsWarningIcon.foreground": palette.rawSienna,
    "panel.background": palette.bunker,
    "panel.border": palette.bunker,
    "panelTitle.activeBorder": palette.riverBed,
    "panelTitle.activeForeground": palette.riverBed,
    "panelTitle.inactiveForeground": palette.heather,
    "peekView.border": palette.limedSpruce,
    "peekViewEditor.background": palette.mirage2,
    "peekViewEditor.matchHighlightBackground": palette.limedSpruce,
    "peekViewEditorGutter.background": palette.limedSpruce,
    "peekViewResult.background": palette.mirage2,
    "peekViewResult.fileForeground": palette.heather,
    "peekViewResult.lineForeground": palette.ecruWhite,
    "peekViewResult.matchHighlightBackground": palette.limedSpruce,
    "peekViewResult.selectionBackground": palette.limedSpruce,
    "peekViewResult.selectionForeground": palette.ecruWhite,
    "peekViewTitle.background": palette.mirage2,
    "peekViewTitleDescription.foreground": palette.heather,
    "peekViewTitleLabel.foreground": palette.mineralGreen,
    "pickerGroup.border": palette.limedSpruce,
    "pickerGroup.foreground": palette.heather,
    "ports.iconRunningProcessForeground": palette.apple,
    "progressBar.background": palette.mineralGreen,
    "scrollbar.shadow": `${palette.black}00`,
    "scrollbarSlider.activeBackground": palette.limedSpruce,
    "scrollbarSlider.background": `${palette.riverBed}80`,
    "scrollbarSlider.hoverBackground": `${palette.riverBed}cc`,
    "selection.background": palette.azureRadiance,
    "sideBar.background": palette.bunker,
    "sideBar.border": palette.ebonyClay,
    "sideBar.foreground": palette.heather,
    "sideBarSectionHeader.background": palette.ebonyClay,
    "sideBarSectionHeader.border": `${palette.silver}33`,
    "sideBarSectionHeader.foreground": palette.heather,
    "sideBarTitle.foreground": palette.heather,
    "statusBar.background": palette.bunker,
    "statusBar.border": palette.ebonyClay,
    "statusBar.debuggingBackground": palette.heather,
    "statusBar.debuggingForeground": palette.bunker,
    "statusBar.foreground": palette.heather,
    "statusBar.noFolderBackground": palette.bunker,
    "statusBar.noFolderForeground": palette.heather,
    "statusBarItem.activeBackground": palette.limedSpruce,
    "statusBarItem.hoverBackground": palette.limedSpruce,
    "statusBarItem.prominentBackground": palette.bunker,
    "statusBarItem.prominentHoverBackground": palette.limedSpruce,
    "statusBarItem.remoteBackground": palette.genoa,
    "statusBarItem.remoteForeground": palette.ecruWhite,
    "tab.activeBackground": palette.ebonyClay,
    "tab.activeBorder": palette.ebonyClay,
    "tab.activeForeground": palette.ecruWhite,
    "tab.border": palette.bunker,
    "tab.inactiveBackground": palette.bunker,
    "tab.inactiveForeground": palette.heather,
    "tab.lastPinnedBorder": `${palette.silver}33`,
    "tab.unfocusedActiveForeground": palette.heather,
    "tab.unfocusedInactiveForeground": palette.heather,
    "terminal.ansiBlack": palette.riverBed,
    "terminal.ansiBlue": palette.dodgerBlue2,
    "terminal.ansiBrightBlack": palette.riverBed,
    "terminal.ansiBrightBlue": palette.dodgerBlue2,
    "terminal.ansiBrightCyan": palette.turquoiseBlue,
    "terminal.ansiBrightGreen": palette.vistaBlue,
    "terminal.ansiBrightMagenta": palette.fuchsiaPink,
    "terminal.ansiBrightRed": palette.cabaret,
    "terminal.ansiBrightWhite": palette.ecruWhite,
    "terminal.ansiBrightYellow": palette.tacao,
    "terminal.ansiCyan": palette.turquoiseBlue,
    "terminal.ansiGreen": palette.vistaBlue,
    "terminal.ansiMagenta": palette.hibiscus,
    "terminal.ansiRed": palette.cabaret,
    "terminal.ansiWhite": palette.ecruWhite,
    "terminal.ansiYellow": palette.tacao,
    "terminal.background": palette.bunker,
    "terminal.foreground": palette.ecruWhite,
    "terminalCursor.background": palette.cuttySark,
    "terminalCursor.foreground": palette.cuttySark,
    "textBlockQuote.background": palette.heather,
    "textBlockQuote.border": palette.heather,
    "textCodeBlock.background": `${palette.heather}33`,
    "textLink.activeForeground": palette.bermudaGray,
    "textLink.foreground": palette.bermudaGray,
    "textPreformat.foreground": palette.bermudaGray,
    "textSeparator.foreground": palette.bermudaGray,
    "titleBar.activeBackground": palette.bunker,
    "titleBar.activeForeground": palette.ecruWhite,
    "titleBar.inactiveBackground": palette.ebonyClay,
    "titleBar.inactiveForeground": `${palette.ecruWhite}33`,
    "walkThrough.embeddedEditorBackground": palette.ebonyClay,
    "widget.shadow": `${palette.black}26`,
    //"activityBar.activeBorder": palette.ecruWhite,
    //"activityBar.dropBorder": palette.ecruWhite,
    //"activityBar.inactiveForeground": "#faf9f166",
    //"banner.background": palette.ebonyClay4,
    //"banner.foreground": palette.heather,
    //"banner.iconForeground": "#3794ff",
    //"breadcrumb.background": palette.ebonyClay,
    //"button.border": "#faf9f100",
    //"button.secondaryBackground": "#3a3d41",
    //"button.secondaryForeground": palette.ecruWhite,
    //"button.secondaryHoverBackground": "#45494e",
    //"charts.blue": "#3794ff",
    //"charts.foreground": palette.heather,
    //"charts.green": "#89d185",
    //"charts.lines": `${palette.heather}80`,
    //"charts.orange": "#d18616",
    //"charts.purple": "#b180d7",
    //"charts.red": palette.deepBlush,
    //"charts.yellow": palette.tacao,
    //"checkbox.background": palette.riverBed,
    //"checkbox.border": palette.riverBed,
    //"checkbox.foreground": palette.ecruWhite,
    //"commandCenter.activeBackground": "#5a5d5e50",
    //"commandCenter.activeForeground": palette.ecruWhite,
    //"commandCenter.border": palette.bunker,
    //"commandCenter.foreground": palette.ecruWhite,
    //"debugConsole.errorForeground": palette.deepBlush,
    //"debugConsole.infoForeground": "#3794ff",
    //"debugConsole.sourceForeground": palette.heather,
    //"debugConsole.warningForeground": palette.tacao,
    //"debugConsoleInputIcon.foreground": palette.heather,
    //"debugIcon.breakpointCurrentStackframeForeground": "#ffcc00",
    //"debugIcon.breakpointDisabledForeground": "#848484",
    //"debugIcon.breakpointForeground": "#e51400",
    //"debugIcon.breakpointStackframeForeground": "#89d185",
    //"debugIcon.breakpointUnverifiedForeground": "#848484",
    //"debugIcon.continueForeground": "#75beff",
    //"debugIcon.disconnectForeground": "#f48771",

    //"debugIcon.stepBackForeground": "#75beff",
    //"debugIcon.stepIntoForeground": "#75beff",
    //"debugIcon.stepOutForeground": "#75beff",
    //"debugIcon.stepOverForeground": "#75beff",

    //"debugTokenExpression.boolean": "#4e94ce",
    //"debugTokenExpression.error": "#f48771",
    //"debugTokenExpression.name": palette.viola,
    //"debugTokenExpression.number": palette.coriander,
    //"debugTokenExpression.string": palette.myPink,
    //"debugTokenExpression.value": "#cccccc99",
    //"debugView.exceptionLabelBackground": "#6c2022",
    //"debugView.exceptionLabelForeground": palette.heather,
    //"debugView.stateLabelBackground": "#88888844",
    //"debugView.stateLabelForeground": palette.heather,
    //"debugView.valueChangedHighlight": palette.havelockBlue,
    //"diffEditor.diagonalFill": `${palette.silver}33`,
    //"disabledForeground": "#cccccc80",
    //"editor.focusedStackFrameHighlightBackground": "#7abd7a4d",
    //"editor.foldBackground": "#3a454e4d",
    //"editor.inlineValuesBackground": "#ffc80033",
    //"editor.inlineValuesForeground": "#faf9f180",
    //"editor.linkedEditingBackground": "#ff00004d",
    //"editor.snippetFinalTabstopHighlightBorder": "#525252",
    //"editor.snippetTabstopHighlightBackground": "#7c7c7c4d",
    //"editor.stackFrameHighlightBackground": "#ffff0033",
    //"editor.symbolHighlightBackground": `${palette.heather}30`,
    //"editorActiveLineNumber.foreground": "#c6c6c6",

    // "editorBracketHighlight.foreground4": "#00000000",
    // "editorBracketHighlight.foreground5": "#00000000",
    // "editorBracketHighlight.foreground6": "#00000000"
    //"editorBracketHighlight.unexpectedBracket.foreground": "#ff1212cc",
    //"editorBracketPairGuide.activeBackground1": "#00000000",
    //"editorBracketPairGuide.activeBackground2": "#00000000",
    //"editorBracketPairGuide.activeBackground3": "#00000000",
    //"editorBracketPairGuide.activeBackground4": "#00000000",
    //"editorBracketPairGuide.activeBackground5": "#00000000",
    //"editorBracketPairGuide.activeBackground6": "#00000000",
    //"editorBracketPairGuide.background1": "#00000000",
    //"editorBracketPairGuide.background2": "#00000000",
    //"editorBracketPairGuide.background3": "#00000000",
    //"editorBracketPairGuide.background4": "#00000000",
    //"editorBracketPairGuide.background5": "#00000000",
    //"editorBracketPairGuide.background6": "#00000000",
    //"editorCommentsWidget.rangeActiveBackground": "#333f4a1a",
    //"editorCommentsWidget.rangeActiveBorder": "#333f4a66",
    //"editorCommentsWidget.rangeBackground": "#333f4a1a",
    //"editorCommentsWidget.rangeBorder": "#333f4a66",
    //"editorCommentsWidget.resolvedBorder": "#cccccc80",
    //"editorCommentsWidget.unresolvedBorder": palette.limedSpruce,
    //"editorGhostText.foreground": "#faf9f156",
    //"editorGroup.dropIntoPromptBackground": palette.mirage2,
    //"editorGroup.dropIntoPromptForeground": palette.heather,
    //"editorGutter.commentRangeForeground": "#c5c5c5",
    //"editorGutter.foldingControlForeground": "#c5c5c5",
    //"editorHint.foreground": "#eeeeeeb3",
    //"editorHoverWidget.foreground": palette.heather,
    //"editorHoverWidget.highlightForeground": palette.mineralGreen,
    //"editorHoverWidget.statusBarBackground": "#192a36",
    //"editorInfo.foreground": "#3794ff",
    //"editorInlayHint.background": "#5ec4ff99",
    //"editorInlayHint.foreground": "#181e24cc",
    //"editorInlayHint.parameterBackground": "#5ec4ff99",
    //"editorInlayHint.parameterForeground": "#181e24cc",
    //"editorInlayHint.typeBackground": "#5ec4ff99",
    //"editorInlayHint.typeForeground": "#181e24cc",
    //"editorLightBulb.foreground": "#ffcc00",
    //"editorLightBulbAutoFix.foreground": "#75beff",
    //"editorLineNumber.activeForeground": "#c6c6c6",
    //"editorMarkerNavigationError.headerBackground": "#d954681a",
    //"editorMarkerNavigationInfo.background": "#3794ff",
    //"editorMarkerNavigationInfo.headerBackground": "#3794ff1a",
    //"editorMarkerNavigationWarning.headerBackground": "#d98e481a",
    //"editorOverviewRuler.addedForeground": "#8bd49c99",
    //"editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
    //"editorOverviewRuler.deletedForeground": "#e27e8d99",
    //"editorOverviewRuler.errorForeground": "#ff1212b3",
    //"editorOverviewRuler.findMatchForeground": "#d186167e",
    //"editorOverviewRuler.infoForeground": "#3794ff",
    //"editorOverviewRuler.modifiedForeground": "#26506d99",
    //"editorOverviewRuler.rangeHighlightForeground": "#007acc99",
    //"editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
    //"editorOverviewRuler.warningForeground": palette.tacao,
    //"editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
    //"editorOverviewRuler.wordHighlightStrongForeground": "#c0a0c0cc",
    //"editorPane.background": palette.ebonyClay,
    //"editorSuggestWidget.focusHighlightForeground": palette.mineralGreen,
    //"editorSuggestWidget.selectedForeground": palette.heather,
    //"editorSuggestWidget.selectedIconForeground": palette.ecruWhite,
    //"editorSuggestWidgetStatus.foreground": `${palette.heather}80`,
    //"editorUnicodeHighlight.background": "#bd9b0326",
    //"editorUnicodeHighlight.border": "#bd9b03",
    //"editorUnnecessaryCode.opacity": "#000000aa",
    //"editorWidget.foreground": palette.heather,
    //"extensionBadge.remoteBackground": palette.heather,
    //"extensionBadge.remoteForeground": palette.mirage,
    //"extensionIcon.preReleaseForeground": "#1d9271",
    //"extensionIcon.sponsorForeground": "#d758b3",
    //"extensionIcon.starForeground": "#ff8e00",
    //"extensionIcon.verifiedForeground": palette.bermudaGray,
    //"gitDecoration.renamedResourceForeground": "#73c991",
    //"gitDecoration.stageDeletedResourceForeground": "#c74e39",
    //"gitDecoration.stageModifiedResourceForeground": "#e2c08d",
    //"gitDecoration.submoduleResourceForeground": "#8db9e2",
    //"icon.foreground": "#c5c5c5",
    //"inputOption.activeBackground": "#333f4a66",
    //"inputOption.activeForeground": palette.ecruWhite,
    //"inputOption.hoverBackground": "#5a5d5e80",
    //"interactive.activeCodeBorder": palette.limedSpruce,
    //"interactive.inactiveCodeBorder": palette.limedSpruce,
    //"keybindingLabel.background": "#8080802b",
    //"keybindingLabel.border": "#33333399",
    //"keybindingLabel.bottomBorder": "#44444499",
    //"keybindingLabel.foreground": "#cccccc",
    //"keybindingTable.headerBackground": "#b7c5d30a",
    //"keybindingTable.rowsBackground": "#b7c5d30a",
    //"list.deemphasizedForeground": "#8c8c8c",
    //"list.errorForeground": "#f88070",
    //"list.filterMatchBackground": `${palette.heather}30`,
    //"list.focusHighlightForeground": palette.mineralGreen,
    //"list.focusOutline": palette.limedSpruce,
    //"list.invalidItemForeground": "#b89500",
    //"list.warningForeground": "#cca700",
    //"listFilterWidget.background": "#653723",
    //"listFilterWidget.noMatchesOutline": "#be1100",
    //"listFilterWidget.outline": "#00000000",
    //"menu.selectionBackground": palette.ebonyClay4,
    //"menu.selectionForeground": palette.heather,
    //"menu.separatorBackground": "#606060",
    //"menubar.selectionBackground": "#5a5d5e50",
    //"menubar.selectionForeground": palette.ecruWhite,
    //"merge.commonContentBackground": "#60606029",
    //"merge.commonHeaderBackground": "#60606066",
    //"merge.currentContentBackground": "#40c8ae33",
    //"merge.currentHeaderBackground": "#40c8ae80",
    //"merge.incomingContentBackground": "#40a6ff33",
    //"merge.incomingHeaderBackground": "#40a6ff80",
    //"mergeEditor.change.background": "#9bb95533",
    //"mergeEditor.change.word.background": "#9bb9551e",
    //"mergeEditor.conflict.handled.minimapOverViewRuler": "#adaca8ee",
    //"mergeEditor.conflict.handledFocused.border": "#c1c1c1cc",
    //"mergeEditor.conflict.handledUnfocused.border": "#86868649",
    //"mergeEditor.conflict.unhandled.minimapOverViewRuler": "#fcba03",
    //"mergeEditor.conflict.unhandledFocused.border": "#ffa600",
    //"mergeEditor.conflict.unhandledUnfocused.border": "#ffa6007a",
    //"notebook.cellBorderColor": palette.limedSpruce,
    //"notebook.cellEditorBackground": palette.bunker,
    //"notebook.cellInsertionIndicator": palette.limedSpruce,
    //"notebook.cellStatusBarItemHoverBackground": "#faf9f126",
    //"notebook.cellToolbarSeparator": "#80808059",
    //"notebook.editorBackground": palette.ebonyClay,
    //"notebook.focusedCellBorder": palette.limedSpruce,
    //"notebook.focusedEditorBorder": palette.limedSpruce,
    //"notebook.inactiveFocusedCellBorder": palette.limedSpruce,
    //"notebook.selectedCellBackground": palette.limedSpruce,
    //"notebook.selectedCellBorder": palette.limedSpruce,
    //"notebook.symbolHighlightBackground": "#faf9f10b",
    //"notebookScrollbarSlider.activeBackground": palette.limedSpruce,
    //"notebookScrollbarSlider.background": `${palette.riverBed}80`,
    //"notebookScrollbarSlider.hoverBackground": "#41505ecc",
    //"notebookStatusErrorIcon.foreground": palette.deepBlush,
    //"notebookStatusRunningIcon.foreground": palette.heather,
    //"notebookStatusSuccessIcon.foreground": "#89d185",
    //"panel.dropBorder": palette.riverBed,
    //"panelSection.border": palette.bunker,
    //"panelSection.dropBackground": palette.limedSpruce,
    //"panelSectionHeader.background": "#80808033",
    //"panelSectionHeader.border": "#faf9f100",
    //"problemsErrorIcon.foreground": palette.deepBlush,
    //"problemsInfoIcon.foreground": "#3794ff",
    //"problemsWarningIcon.foreground": palette.tacao,
    //"quickInput.background": palette.mirage2,
    //"quickInput.foreground": palette.heather,
    //"quickInputList.focusBackground": palette.ebonyClay4,
    //"quickInputList.focusForeground": palette.heather,
    //"quickInputList.focusIconForeground": palette.ecruWhite,
    //"quickInputTitle.background": "#faf9f11b",
    //"sash.hoverBorder": palette.limedSpruce,
    //"scm.providerBorder": "#454545",
    //"searchEditor.findMatchBackground": "#b7c5d320",
    //"searchEditor.textInputBorder": palette.limedSpruce,
    //"settings.checkboxBackground": palette.riverBed,
    //"settings.checkboxBorder": palette.riverBed,
    //"settings.checkboxForeground": palette.ecruWhite,
    //"settings.dropdownBackground": palette.riverBed,
    //"settings.dropdownBorder": palette.riverBed,
    //"settings.dropdownForeground": palette.ecruWhite,
    //"settings.dropdownListBorder": palette.limedSpruce,
    //"settings.focusedRowBackground": "#1d252c99",
    //"settings.focusedRowBorder": "#faf9f11f",
    //"settings.headerBorder": palette.bunker,
    //"settings.headerForeground": "#e7e7e7",
    //"settings.modifiedItemIndicator": "#0c7d9d",
    //"settings.numberInputBackground": palette.limedSpruce,
    //"settings.numberInputBorder": palette.limedSpruce,
    //"settings.numberInputForeground": palette.heather,
    //"settings.rowHoverBackground": "#1d252c4d",
    //"settings.sashBorder": palette.bunker,
    //"settings.textInputBackground": palette.limedSpruce,
    //"settings.textInputBorder": palette.limedSpruce,
    //"settings.textInputForeground": palette.heather,
    //"sideBar.dropBackground": palette.limedSpruce,
    //"sideBySideEditor.horizontalBorder": palette.ebonyClay,
    //"sideBySideEditor.verticalBorder": palette.ebonyClay,
    //"statusBar.debuggingBorder": palette.ebonyClay,
    //"statusBar.focusBorder": palette.heather,
    //"statusBar.noFolderBorder": palette.ebonyClay,
    //"statusBarItem.compactHoverBackground": `${palette.ecruWhite}33`,
    //"statusBarItem.errorBackground": "#ac273b",
    //"statusBarItem.errorForeground": palette.ecruWhite,
    //"statusBarItem.focusBorder": palette.heather,
    //"statusBarItem.prominentForeground": palette.heather,
    //"statusBarItem.warningBackground": "#bd7b1f",
    //"statusBarItem.warningForeground": palette.ecruWhite,
    //"symbolIcon.arrayForeground": palette.heather,
    //"symbolIcon.booleanForeground": palette.heather,
    //"symbolIcon.classForeground": "#ee9d28",
    //"symbolIcon.colorForeground": palette.heather,
    //"symbolIcon.constantForeground": palette.heather,
    //"symbolIcon.constructorForeground": "#b180d7",
    //"symbolIcon.enumeratorForeground": "#ee9d28",
    //"symbolIcon.enumeratorMemberForeground": "#75beff",
    //"symbolIcon.eventForeground": "#ee9d28",
    //"symbolIcon.fieldForeground": "#75beff",
    //"symbolIcon.fileForeground": palette.heather,
    //"symbolIcon.folderForeground": palette.heather,
    //"symbolIcon.functionForeground": "#b180d7",
    //"symbolIcon.interfaceForeground": "#75beff",
    //"symbolIcon.keyForeground": palette.heather,
    //"symbolIcon.keywordForeground": palette.heather,
    //"symbolIcon.methodForeground": "#b180d7",
    //"symbolIcon.moduleForeground": palette.heather,
    //"symbolIcon.namespaceForeground": palette.heather,
    //"symbolIcon.nullForeground": palette.heather,
    //"symbolIcon.numberForeground": palette.heather,
    //"symbolIcon.objectForeground": palette.heather,
    //"symbolIcon.operatorForeground": palette.heather,
    //"symbolIcon.packageForeground": palette.heather,
    //"symbolIcon.propertyForeground": palette.heather,
    //"symbolIcon.referenceForeground": palette.heather,
    //"symbolIcon.snippetForeground": palette.heather,
    //"symbolIcon.stringForeground": palette.heather,
    //"symbolIcon.structForeground": palette.heather,
    //"symbolIcon.textForeground": palette.heather,
    //"symbolIcon.typeParameterForeground": palette.heather,
    //"symbolIcon.unitForeground": palette.heather,
    //"symbolIcon.variableForeground": "#75beff",
    //"tab.activeModifiedBorder": "#3399cc",
    //"tab.inactiveModifiedBorder": "#3399cc80",
    //"tab.unfocusedActiveBackground": palette.ebonyClay,
    //"tab.unfocusedActiveBorder": "#1d252c80",
    //"tab.unfocusedActiveModifiedBorder": "#3399cc80",
    //"tab.unfocusedInactiveBackground": palette.bunker,
    //"tab.unfocusedInactiveModifiedBorder": "#3399cc40",
    //"terminal.border": palette.bunker,
    //"terminal.dropBackground": palette.limedSpruce,
    //"terminal.findMatchBackground": `${palette.heather}80`,
    //"terminal.findMatchHighlightBackground": `${palette.heather}30`,
    //"terminal.selectionBackground": "#bada55",
    //"terminal.tab.activeBorder": palette.ebonyClay,
    //"terminalCommandDecoration.defaultBackground": "#faf9f140",
    //"terminalCommandDecoration.errorBackground": "#f14c4c",
    //"terminalCommandDecoration.successBackground": "#1b81a8",
    //"terminalOverviewRuler.cursorForeground": "#a0a0a0cc",
    //"terminalOverviewRuler.findMatchForeground": "#d186167e",
    //"testing.iconErrored": "#f14c4c",
    //"testing.iconFailed": "#f14c4c",
    //"testing.iconPassed": "#73c991",
    //"testing.iconQueued": "#cca700",
    //"testing.iconSkipped": "#848484",
    //"testing.iconUnset": "#848484",
    //"testing.message.error.decorationForeground": palette.deepBlush,
    //"testing.message.error.lineBackground": "#ff000033",
    //"testing.message.info.decorationForeground": `${palette.heather}80`,
    //"testing.peekBorder": palette.deepBlush,
    //"testing.peekHeaderBackground": "#e27e8d1a",
    //"testing.runAction": "#73c991",
    //"toolbar.activeBackground": "#63666750",
    //"toolbar.hoverBackground": "#5a5d5e50",
    //"tree.indentGuidesStroke": "#585858",
    //"tree.tableColumnsBorder": "#cccccc20",
    //"tree.tableOddRowsBackground": "#b7c5d30a",
    //"welcomePage.progress.background": palette.limedSpruce,
    //"welcomePage.progress.foreground": palette.bermudaGray,
    //"welcomePage.tileBackground": palette.mirage2,
    //"welcomePage.tileHoverBackground": "#192a36",
    //"welcomePage.tileShadow": "#00000026",
    //"activityBar.activeBackground": null,
    //"activityBar.activeFocusBorder": null,
    //"commandCenter.background": null,
    //"contrastActiveBorder": null,
    //"diffEditor.border": null,
    //"diffEditor.insertedLineBackground": null,
    //"diffEditor.removedLineBackground": null,
    //"diffEditorGutter.insertedLineBackground": null,
    //"diffEditorGutter.removedLineBackground": null,
    //"diffEditorOverview.insertedForeground": null,
    //"diffEditorOverview.removedForeground": null,
    //"dropdown.listBackground": null,
    //"editor.findMatchBorder": null,
    //"editor.findMatchHighlightBorder": null,
    //"editor.findRangeHighlightBorder": null,
    //"editor.rangeHighlightBorder": null,
    //"editor.selectionForeground": null,
    //"editor.selectionHighlightBorder": null,
    //"editor.snippetFinalTabstopHighlightBackground": null,
    //"editor.snippetTabstopHighlightBorder": null,
    //"editor.symbolHighlightBorder": null,
    //"editor.wordHighlightBorder": null,
    //"editor.wordHighlightStrongBorder": null,
    //"editorCursor.background": null,
    //"editorError.background": null,
    //"editorGhostText.background": null,
    //"editorGhostText.border": null,
    //"editorGroup.dropIntoPromptBorder": null,
    //"editorGroup.focusedEmptyBorder": null,
    //"editorGroupHeader.border": null,
    //"editorHint.border": null,
    //"editorInfo.background": null,
    //"editorInfo.border": null,
    //"editorOverviewRuler.background": null,
    //"editorUnnecessaryCode.border": null,
    //"editorWarning.background": null,
    //"editorWidget.resizeBorder": null,
    //"inputValidation.infoForeground": null,
    //"list.filterMatchBorder": null,
    //"list.focusAndSelectionOutline": null,
    //"list.inactiveFocusBackground": null,
    //"list.inactiveFocusOutline": null,
    //"list.inactiveSelectionIconForeground": null,
    //"menu.border": null,
    //"menu.selectionBorder": null,
    //"menubar.selectionBorder": null,
    //"merge.border": null,
    //"minimap.background": null,
    //"notebook.cellHoverBackground": null,
    //"notebook.focusedCellBackground": null,
    //"notebook.inactiveSelectedCellBorder": null,
    //"notebook.outputContainerBackgroundColor": null,
    //"notebook.outputContainerBorderColor": null,
    //"notificationCenter.border": null,
    //"notificationCenterHeader.foreground": null,
    //"notificationToast.border": null,
    //"panelInput.border": null,
    //"panelSectionHeader.foreground": null,
    //"peekViewEditor.matchHighlightBorder": null,
    //"quickInput.list.focusBackground": null,
    //"searchEditor.findMatchBorder": null,
    //"statusBarItem.settingsProfilesBackground": null,
    //"statusBarItem.settingsProfilesForeground": null,
    //"tab.activeBorderTop": null,
    //"tab.hoverBackground": null,
    //"tab.hoverBorder": null,
    //"tab.hoverForeground": null,
    //"tab.unfocusedActiveBorderTop": null,
    //"tab.unfocusedHoverBackground": null,
    //"tab.unfocusedHoverBorder": null,
    //"tab.unfocusedHoverForeground": null,
    //"terminal.findMatchBorder": null,
    //"terminal.findMatchHighlightBorder": null,
    //"terminal.selectionForeground": null,
    //"testing.message.info.lineBackground": null,
    //"titleBar.border": null,
    //"toolbar.hoverOutline": null,
    //"welcomePage.background": null,
    //"window.activeBorder": null,
    //"window.inactiveBorder": null
  },
  tokenColors: [
    {
      scope: ["meta.embedded", "source.groovy.embedded"],
      settings: {
        foreground: palette.alto,
      },
    },
    {
      scope: "emphasis",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "strong",
      settings: {
        fontStyle: "bold",
      },
    },
    {
      scope: "header",
      settings: {
        foreground: palette.navyBlue,
      },
    },
    {
      scope: "comment",
      settings: {
        foreground: palette.fernGreen,
      },
    },
    {
      scope: "constant.language",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: [
        "constant.numeric",
        "variable.other.enummember",
        "keyword.operator.plus.exponent",
        "keyword.operator.minus.exponent",
      ],
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      scope: "constant.regexp",
      settings: {
        foreground: palette.kimberly,
      },
    },
    {
      scope: "entity.name.tag",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "entity.name.tag.css",
      settings: {
        foreground: palette.straw,
      },
    },
    {
      scope: "entity.other.attribute-name",
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: [
        "entity.other.attribute-name.class.css",
        "entity.other.attribute-name.class.mixin.css",
        "entity.other.attribute-name.id.css",
        "entity.other.attribute-name.parent-selector.css",
        "entity.other.attribute-name.pseudo-class.css",
        "entity.other.attribute-name.pseudo-element.css",
        "source.css.less entity.other.attribute-name.id",
        "entity.other.attribute-name.scss",
      ],
      settings: {
        foreground: palette.straw,
      },
    },
    {
      scope: "invalid",
      settings: {
        foreground: palette.deepBlush,
      },
    },
    {
      scope: "markup.underline",
      settings: {
        fontStyle: "underline",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        foreground: palette.havelockBlue,
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.heading",
      settings: {
        foreground: palette.havelockBlue,
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.strikethrough",
      settings: {
        fontStyle: "strikethrough",
      },
    },
    {
      scope: "markup.inserted",
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      name: "Deleted line markup",
      scope: "markup.deleted",
      settings: {
        foreground: palette.deepBlush,
      },
    },
    {
      name: "Changed line markup",
      scope: "markup.changed",
      settings: {
        foreground: palette.tacao,
      },
    },
    {
      scope: [
        "punctuation.terminator.statement",
        "keyword.operator.assignment",
        "keyword.operator.comparison",
        "punctuation.separator.key-value",
        "keyword.operator.type.annotation",
      ],
      settings: {
        foreground: palette.bermudaGray,
      },
    },
    {
      scope: "punctuation.definition.quote.begin.markdown",
      settings: {
        foreground: palette.chaletGreen,
      },
    },
    {
      scope: "punctuation.definition.list.begin.markdown",
      settings: {
        foreground: palette.cornflowerBlue,
      },
    },
    {
      scope: "markup.inline.raw",
      settings: {
        foreground: `${palette.myPink}ec`,
      },
    },
    {
      scope: "punctuation.definition.tag",
      settings: {
        foreground: palette.gray,
      },
    },
    {
      scope: ["meta.preprocessor", "entity.name.function.preprocessor"],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "meta.preprocessor.string",
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: "meta.preprocessor.numeric",
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      scope: "meta.structure.dictionary.key.python",
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: "meta.diff.header",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "storage",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "storage.type",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: ["storage.modifier", "keyword.operator.noexcept"],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: ["string", "meta.embedded.assembly"],
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: "string.tag",
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: "string.value",
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: "string.regexp",
      settings: {
        foreground: palette.chestnutRose,
      },
    },
    {
      scope: [
        "punctuation.definition.template-expression.begin",
        "punctuation.definition.template-expression.end",
        "punctuation.section.embedded",
      ],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: ["meta.template.expression"],
      settings: {
        foreground: palette.alto,
      },
    },
    {
      scope: [
        "support.type.vendored.property-name",
        "support.type.property-name",
        "variable.css",
        "variable.scss",
        "variable.other.less",
        "source.coffee.embedded",
      ],
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: "keyword",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "keyword.control",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "keyword.operator",
      settings: {
        foreground: palette.alto,
      },
    },
    {
      scope: [
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.cast",
        "keyword.operator.sizeof",
        "keyword.operator.alignof",
        "keyword.operator.typeid",
        "keyword.operator.alignas",
        "keyword.operator.instanceof",
        "keyword.operator.logical.python",
        "keyword.operator.wordlike",
      ],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "keyword.other.unit",
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      scope: [
        "punctuation.section.embedded.begin.php",
        "punctuation.section.embedded.end.php",
      ],
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "support.function.git-rebase",
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: "constant.sha.git-rebase",
      settings: {
        foreground: palette.coriander,
      },
    },
    {
      scope: [
        "storage.modifier.import.java",
        "variable.language.wildcard.java",
        "storage.modifier.package.java",
      ],
      settings: {
        foreground: palette.alto,
      },
    },
    {
      scope: "variable.language",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: [
        "entity.name.function",
        "support.function",
        "support.constant.handlebars",
        "source.powershell variable.other.member",
        "entity.name.operator.custom-literal",
      ],
      settings: {
        foreground: palette.sapling,
      },
    },
    {
      scope: [
        "support.class",
        "support.type",
        "entity.name.type",
        "entity.name.namespace",
        "entity.other.attribute",
        "entity.name.scope-resolution",
        "entity.name.class",
        "storage.type.numeric.go",
        "storage.type.byte.go",
        "storage.type.boolean.go",
        "storage.type.string.go",
        "storage.type.uintptr.go",
        "storage.type.error.go",
        "storage.type.rune.go",
        "storage.type.cs",
        "storage.type.generic.cs",
        "storage.type.modifier.cs",
        "storage.type.variable.cs",
        "storage.type.annotation.java",
        "storage.type.generic.java",
        "storage.type.java",
        "storage.type.object.array.java",
        "storage.type.primitive.array.java",
        "storage.type.primitive.java",
        "storage.type.token.java",
        "storage.type.groovy",
        "storage.type.annotation.groovy",
        "storage.type.parameters.groovy",
        "storage.type.generic.groovy",
        "storage.type.object.array.groovy",
        "storage.type.primitive.array.groovy",
        "storage.type.primitive.groovy",
      ],
      settings: {
        foreground: palette.puertoRico,
      },
    },
    {
      scope: [
        "meta.type.cast.expr",
        "meta.type.new.expr",
        "support.constant.math",
        "support.constant.dom",
        "support.constant.json",
        "entity.other.inherited-class",
      ],
      settings: {
        foreground: palette.puertoRico,
      },
    },
    {
      scope: [
        "keyword.control",
        "source.cpp keyword.operator.new",
        "keyword.operator.delete",
        "keyword.other.using",
        "keyword.other.operator",
        "entity.name.operator",
      ],
      settings: {
        foreground: palette.viola,
      },
    },
    {
      scope: [
        "variable",
        "meta.definition.variable.name",
        "support.variable",
        "entity.name.variable",
        "constant.other.placeholder",
      ],
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: ["variable.other.constant", "variable.other.enummember"],
      settings: {
        foreground: palette.malibu,
      },
    },
    {
      scope: ["meta.object-literal.key"],
      settings: {
        foreground: palette.anakiwa,
      },
    },
    {
      scope: [,],
      settings: {
        foreground: `${palette.anakiwa}c0`,
      },
    },
    {
      scope: [
        "support.constant.property-value",
        "support.constant.font-name",
        "support.constant.media-type",
        "support.constant.media",
        "constant.other.color.rgb-value",
        "constant.other.rgb-value",
        "support.constant.color",
      ],
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: [
        "punctuation.definition.group.regexp",
        "punctuation.definition.group.assertion.regexp",
        "punctuation.definition.character-class.regexp",
        "punctuation.character.set.begin.regexp",
        "punctuation.character.set.end.regexp",
        "keyword.operator.negation.regexp",
        "support.other.parenthesis.regexp",
      ],
      settings: {
        foreground: palette.myPink,
      },
    },
    {
      scope: [
        "constant.character.character-class.regexp",
        "constant.other.character-class.set.regexp",
        "constant.other.character-class.regexp",
        "constant.character.set.regexp",
      ],
      settings: {
        foreground: palette.chestnutRose,
      },
    },
    {
      scope: [
        "keyword.control.import",
        "keyword.control.export",
        "keyword.control.from",
      ],
      settings: {
        foreground: `${palette.viola}b0`,
      },
    },
    {
      scope: ["keyword.operator.or.regexp", "keyword.control.anchor.regexp"],
      settings: {
        foreground: palette.sapling,
      },
    },
    {
      scope: "keyword.operator.quantifier.regexp",
      settings: {
        foreground: palette.straw,
      },
    },
    {
      scope: "constant.character",
      settings: {
        foreground: palette.havelockBlue,
      },
    },
    {
      scope: "constant.character.escape",
      settings: {
        foreground: palette.straw,
      },
    },
    {
      scope: "entity.name.label",
      settings: {
        foreground: palette.silver,
      },
    },
    {
      scope: "token.info-token",
      settings: {
        foreground: palette.cornflowerBlue,
      },
    },
    {
      scope: "token.warn-token",
      settings: {
        foreground: palette.hokeyPokey,
      },
    },
    {
      scope: "token.error-token",
      settings: {
        foreground: palette.deepBlush,
      },
    },
    {
      scope: "token.debug-token",
      settings: {
        foreground: palette.mediumPurlple,
      },
    },
    {
      name: "Inserted line markup",
      scope: "markup.inserted",
      settings: {
        foreground: palette.vistaBlue,
      },
    },
    {
      name: "Deleted line markup",
      scope: "markup.deleted",
      settings: {
        foreground: palette.deepBlush,
      },
    },
    {
      name: "Changed line markup",
      scope: "markup.changed",
      settings: {
        foreground: palette.tacao,
      },
    },
  ],
}
